export const AGENTS = [
  {
    href: "/feasibility",
    code: "01",
    name: "Site kit",
    title: "Site feasibility kit",
    replaces: "Broker compiles zoning, comps, demographics",
    produces: "Ready-to-sign PDF + PandaDoc packet",
    mark: "◈",
  },
  {
    href: "/triage",
    code: "02",
    name: "Triage",
    title: "Tenant ticket triage",
    replaces: "Manager reads maintenance mail",
    produces: "Vendor assigned + SMS both ways",
    mark: "◎",
  },
  {
    href: "/permits",
    code: "03",
    name: "Pulse",
    title: "Permit pulse",
    replaces: "PM refreshes the city portal",
    produces: "Email + Notion timeline",
    mark: "▣",
  },
  {
    href: "/drone",
    code: "04",
    name: "Drone",
    title: "Drone progress",
    replaces: "Super eyeballs weekly photos",
    produces: "% vs BIM, then a human gate",
    mark: "◬",
  },
  {
    href: "/churn",
    code: "05",
    name: "Churn",
    title: "Lease-churn predictor",
    replaces: "Staff guess renewal offers",
    produces: "LightGBM risk + incentive email",
    mark: "◆",
  },
] as const;
