export const AGENTS = [
  {
    href: "/feasibility",
    code: "01",
    name: "Site kit",
    title: "Site feasibility kit",
    replaces: "Broker compiles zoning, comps, demographics",
    produces: "Sample PDF packet + simulated PandaDoc draft",
    sample: "Austin · 1408 East 6th Street",
    action: "Compile kit",
    mark: "◈",
  },
  {
    href: "/triage",
    code: "02",
    name: "Triage",
    title: "Tenant ticket triage",
    replaces: "Manager reads maintenance mail",
    produces: "Trade + vendor pick, with simulated SMS drafts",
    sample: "Burst pipe in the kitchen",
    action: "Triage ticket",
    mark: "◎",
  },
  {
    href: "/permits",
    code: "03",
    name: "Pulse",
    title: "Permit pulse",
    replaces: "PM refreshes the city portal",
    produces: "Status diffs + simulated email / Notion drafts",
    sample: "Four watched demo permits",
    action: "Run pulse",
    mark: "▣",
  },
  {
    href: "/drone",
    code: "04",
    name: "Drone",
    title: "Drone progress",
    replaces: "Super eyeballs weekly photos",
    produces: "% vs BIM, then a superintendent hold",
    sample: "East 6th Lofts flyover",
    action: "Fly the comparison",
    mark: "◬",
  },
  {
    href: "/churn",
    code: "05",
    name: "Churn",
    title: "Lease-churn predictor",
    replaces: "Staff guess renewal offers",
    produces: "Risk scores + simulated renewal drafts",
    sample: "Five anonymous sample leases",
    action: "Score portfolio",
    mark: "◆",
  },
] as const;
